### ISSUE TITLE
 Bug if DB password contain special chars

### ISSUE THREAD

**Issue by tyl3r** [lesterchan/wp-dbmanager#11]
If you want to reproduce the bug in your machine, this is my old password:

!·%/QETU

With this the file output is 0 B in SQL or 20 B in GZIP.

**Comment by lesterchan** [comment]
Unfortunately, I don't have a solution for this for the general because it involves setting locale (and may screw up other sites not using English) and it is the side effect of using escapeshellarg() for security purposes.

I would suggest removing the · in your password or adding this line to database-backup.php
```php
setlocale( LC_CTYPE, 'en_US.UTF-8' );
```
After line 40
```php
$gzip = intval($_POST['gzip']);
```

and to wp-dbmanager.php
```php
setlocale( LC_CTYPE, 'en_US.UTF-8' );
```
After line 84
```php
$brace = (substr(PHP_OS, 0, 3) == 'WIN') ? '"' : '';
```

Alternatively, you can try other plugin like https://wordpress.org/plugins/wp-db-backup/ that uses PHP to generate the backup instead of mysqldump.

**Comment by lesterchan** [comment]
I thought of another way, I added an action called wp_dbmanager_before_escapeshellcmd for the upcoming 2.76.

You can add this to your theme's function.php
```php
add_action( 'wp_dbmanager_before_escapeshellcmd', 'dbmanager_setlocale' );
function dbmanager_setlocale() {
    setlocale( LC_CTYPE, 'en_US.UTF-8' );
}
```php

**Comment by tyl3r** [comment]
I commented this here for helping other users and for tell you that this happens, this bug gave me a lot of headaches trying to find why the plugin don't worked... until i discovered the cause!, my fix was just only change the password :), thx for the answers.

**Comment by lesterchan** [comment]
@tyl3r thanks! Sorry for the troubles.
