### ISSUE TITLE
Daily backup database in WordPress 4.1 is performed multiple times

### ISSUE THREAD

**Issue by Monter** [lesterchan/wp-dbmanager#9]
From December 24 DBManager my every moment makes a copy of the database and sends it by e-mail, despite the existence of only one task in WP_Cron. The task set to 13:00 each day is done until 20:00. I can not locate the cause, the server logs there are no errors (eg. Timeout or something similar). WordPress v4.1. Please help.

**Comment by lesterchan** [comment]
From the API point of view, It can't be deleted because it is recurring event. If it get stuck and keep being executed, it seems to be a bug on WordPress cron side though. It should just fire once regardless whether the outcome is an error or not. I am not sure if there is anything on my end I can do to prevent this besides showing the error outcome (if any).

Nevertheless, I will take note of this to see if there is any similar issue crops up. To be honest, this is the first time I heard of this issue (cron job keeps firing)
